
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  gradientBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  card: {
    width: "90%",
    maxWidth: 430,
    paddingHorizontal: 22,
    paddingTop: 34,
    paddingBottom: 28,
    borderRadius: 28,
    backgroundColor: "#ffffff",
    shadowColor: "#1f6f5f",
    shadowOpacity: 0.14,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 18,
  },
  logoBadge: {
    width: 102,
    height: 102,
    borderRadius: 24,
    backgroundColor: "#2fa084",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#1f6f5f",
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  logoLetter: {
    position: "absolute",
    color: "#ffffff",
    fontSize: 42,
    fontWeight: "700",
    lineHeight: 44,
  },
  title: {
    fontSize: 29,
    fontWeight: "800",
    textAlign: "center",
    color: "#1f6f5f",
  },
  subtitle: {
    marginTop: 12,
    textAlign: "center",
    color: "#1f6f5f",
    fontSize: 17,
    lineHeight: 23,
    opacity: 0.8,
  },
  fieldGroup: {
    marginTop: 26,
  },
  label: {
    marginBottom: 10,
    fontWeight: "700",
    fontSize: 18,
    color: "#1f6f5f",
  },
  input: {
    backgroundColor: "#fcfdfd",
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "rgba(47, 160, 132, 0.35)",
    color: "#1f6f5f",
    fontSize: 17,
  },
  terms: {
    fontSize: 13,
    color: "#1f6f5f",
    marginTop: 24,
    textAlign: "center",
    lineHeight: 20,
    opacity: 0.8,
  },
  link: {
    color: "#2fa084",
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  secondaryButton: {
    marginTop: 28,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: "#f0f9f6",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(47, 160, 132, 0.25)",
  },
  secondaryButtonText: {
    fontWeight: "700",
    fontSize: 17,
    color: "#1f6f5f",
  },
  primaryButton: {
    marginTop: 14,
    backgroundColor: "#1f6f5f",
    paddingVertical: 17,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#1f6f5f",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  primaryButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  primaryButtonDisabled: {
    opacity: 0.75,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 18,
  },
  footer: {
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 6,
    paddingVertical: 18,
  },
  footerText: {
    color: "#1f6f5f",
    fontSize: 13,
    opacity: 0.8,
  },
  footerDivider: {
    color: "#1f6f5f",
    fontSize: 13,
    opacity: 0.8,
  },
  footerLink: {
    color: "#2fa084",
    fontSize: 13,
    fontWeight: "700",
  },
});