import { StyleSheet } from 'react-native';
import { COLORS } from '../../assets/styles/Colores.style';
const C = COLORS;

export const styles = StyleSheet.create({
  screen:          { flex: 1, backgroundColor: C.bg },
  mapContainer:    { height: 240, position: 'relative' },
  map:             { ...StyleSheet.absoluteFillObject },
  mapHeader:       { position: 'absolute', top: 0, left: 0, right: 0, backgroundColor: 'rgba(31,111,95,0.88)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 10 },
  backBtn:         { width: 30, height: 30, borderRadius: 15, backgroundColor: 'rgba(255,255,255,.2)', alignItems: 'center', justifyContent: 'center' },
  mapTitle:        { color: '#fff', fontSize: 13, fontWeight: '600' },
  enRutaBadge:     { backgroundColor: C.light, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3 },
  enRutaText:      { fontSize: 10, fontWeight: '700', color: '#0d4a34' },
  body:            { flex: 1 },
  card:            { backgroundColor: '#fff', borderRadius: 16, borderWidth: 0.5, borderColor: '#ddd', overflow: 'hidden' },
  orderRow:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 14, borderBottomWidth: 0.5, borderBottomColor: '#eee' },
  orderCode:       { fontSize: 17, fontWeight: '700', color: C.primary },
  orderSub:        { fontSize: 11, color: '#888', marginTop: 2 },
  estadoBadge:     { borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
  estadoText:      { fontSize: 10, fontWeight: '700' },
  routeSection:    { padding: 14, borderBottomWidth: 0.5, borderBottomColor: '#eee' },
  routeRow:        { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  routeLine:       { alignItems: 'center', paddingTop: 3 },
  dotStart:        { width: 10, height: 10, borderRadius: 5, backgroundColor: C.teal },
  routeConnector:  { width: 2, flex: 1, backgroundColor: '#c8e8de', marginVertical: 3, minHeight: 24 },
  dotEnd:          { width: 10, height: 10, borderRadius: 5, borderWidth: 2, borderColor: C.primary, backgroundColor: '#fff' },
  routeTexts:      { flex: 1, gap: 16 },
  routeLabel:      { fontSize: 10, color: C.teal, fontWeight: '700', letterSpacing: 0.4, marginBottom: 2 },
  routeValue:      { fontSize: 12, color: '#1a1a1a', lineHeight: 17 },
  infoSection:     { padding: 12 },
  infoGrid:        { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  infoItem:        { flex: 1, minWidth: '45%', backgroundColor: C.metricBg, borderRadius: 10, padding: 9, borderWidth: 0.5, borderColor: C.metricBdr },
  infoFull:        { flexBasis: '100%', flex: undefined },
  infoLabel:       { fontSize: 9, color: C.teal, fontWeight: '700', letterSpacing: 0.3, marginBottom: 3 },
  infoValue:       { fontSize: 13, fontWeight: '600', color: '#1a1a1a' },
  contactRow:      { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 12, paddingHorizontal: 14, borderTopWidth: 0.5, borderTopColor: '#eee' },
  contactName:     { fontSize: 13, fontWeight: '600', color: '#1a1a1a' },
  contactSub:      { fontSize: 10, color: '#888', marginTop: 1 },
  callBtn:         { width: 40, height: 40, borderRadius: 20, backgroundColor: C.teal, alignItems: 'center', justifyContent: 'center' },
});